name: Dynamo
version: '${version}'
main: com.th7bo.dynamo.Dynamo
api-version: '1.19'
depend:
  - PlaceholderAPI
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - Skript
commands:
  test:
    description: Test command
    usage: /<command>
    permission: dynamo.test
    aliases:
      - t
  leaderboards:
    description: Leaderboard command
    usage: /<command>
    permission: dynamo.leaderboard
    aliases:
      - lb