name: Dynamo
version: '${version}'
main: com.th7bo.dynamo.Dynamo
api-version: '1.19'
depend:
  - PlaceholderAPI
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - Skript